### ISSUE TITLE
No homework milestones 

### ISSUE THREAD

**Issue by laserlab** [ubsuny/LLPS-ProteinRNA_Condensates-CP2P2024#2]
Add homework milestones and add my two issues to it

**Comment by tirthbha** [comment]
> Add homework milestones and add my two issues to it

Created!

**Comment by laserlab** [comment]
There is still no milestone for the midterm, please create and add the comment I had about the missing code to it #5

**Comment by tirthbha** [comment]
Issue #2 is added to midterm milestone 
And the reproducing code added
